---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-server
  labels:
    app: nginx-server
spec:
  containers:
    - name: nginx-server-container
      image: nginx
      ports:
        - containerPort: 80
