---
apiVersion: v1
kind: Service
metadata:
  name: nginx-webserver-nodeport-svc
spec:
  type: NodePort
  selector:
    app: nginx-server
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30300
