---
apiVersion: v1
kind: Namespace
metadata:
  name: wjru-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-site-deployment
  namespace: wjru-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: shopping-site-pod
      namespace: wjru-ns
      labels:
        app: shopping-app
        env: dev
        color: blue
    spec:
      containers:
        - name: shopping-app-container
          image: madandevops2024/shoppingsite
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-site-nodeport-svc
  namespace: wjru-ns
spec:
  type: NodePort
  selector:
    color: blue #Pod label which we have created under labels
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31000
---

