apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    storage: amazon-store-db-storage
  name: amazon-store-db-config-map
data:
  DB_DRIVER_NAME_VALUE: com.mysql.cj.jdbc.Driver
  DB_HOST_SERVICE_NAME_VALUE: amazon-store-app-db-service
  DB_PORT_VALUE: "3306"
  DB_SCHEMA_VALUE: amazon-store-app
