apiVersion: v1
kind: PersistentVolume
metadata:
  name: amazon-store-db-pv
  labels:
    name: amazon-store-db-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /opt/mysql
