apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amazon-store-db-pvc
spec:
  volumeName: amazon-store-db-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 4Gi
